apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbucketss.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: xbuckets
    plural: xbucketss
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              names:
                type: array
                items:
                  type: string
            required:
            - region
            - names
        type: object